# plugins/dry-run.toml
["modules/@mindbaz/zonemta-dry-run"]
enabled = true

header = "X-My-Dry-Run"

receivers = [
  "adam.brooks@mail.info",
  "ashley.gonzalez@mail.info",
  "ashley.harrell@mail.info",
]

fakeReceivers = [
  "isThisRealLife@mail.info",
]

sender = "sender@mail.info"
